version: '3'


networks:
  default:
    external:
      name: tools

services:
  v2ray:
    image: v2fly/v2fly-core
    restart: always
    volumes:
      - ./config.json:/etc/v2ray/config.json
    ports:
      - 10086:10086


