version: '3'


services:
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    restart: always


  prometheus:
    image: prom/prometheus:latest
    user: "1000:1000"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # 配置文件
      - ./prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    depends_on:
      - prometheus
    user: "472:472"
    image: grafana/grafana:latest
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always


networks:
  default:
    external:
      name: tools