global:
  scrape_interval:     15s
  evaluation_interval: 15s

#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
#      - alertmanager:9093

rule_files:
  - "*rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # - job_name: baymax
  #   static_configs:
  #     - targets: ['baymax-gate:9080', 'baymax-user:9080','baymax-activity:9080']



#  - job_name: 'node'
#    static_configs:
#      - targets: ['node-exporter:9100','192.168.123.12:9100','192.168.123.13:9100']

#  - job_name: 'alertmanager'
#    static_configs:
#    - targets: ['alertmanager:9093']