version: '3'

networks:
  default:
    external:
      name: tools

services:
  consul1:
    image: consul:latest
    restart: always
    container_name: consul-node1
    command: agent -server -bootstrap -client 0.0.0.0 # -bootstrap 标识该服务是否处于”引导“模式，每个数据中心最多只能运行一台有该配置的服务，有该标识的服务可以自我选举为 leader
  consul2:
    image: consul:latest
    restart: always
    container_name: consul-node2
    command: agent -server -client 0.0.0.0 -retry-join consul-node1
    depends_on:
      - consul1
  consul3:
    image: consul:latest
    restart: always
    container_name: consul-node3
    command: agent -server  -client 0.0.0.0 -retry-join consul-node1
    depends_on:
      - consul1

  consul4: # client
    image: consul:latest
    restart: always
    container_name: consul-node4
    command: agent -ui -client 0.0.0.0 -retry-join consul-node1
    ports:
      - 8500:8500
    depends_on:
      - consul2
      - consul3
