version: "3"


networks:
  default:
    external:
      name: tools

services:
  nginx:
    image: nginx:latest
    restart: always
    networks:
      - default
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sources.list:/etc/apt/sources.list
    ports:
      - "4000:4000"
