version: "3"

networks:
  default:
    external:
      name: tools

services:
  elk:
    image: sebp/elk:latest
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./config/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

