version: "3"

networks:
  default:
    external:
      name: tools

services:
 mysql:
  restart: always
  command:
   --lower_case_table_names=1
   --character-set-server=utf8mb4
   --collation-server=utf8mb4_general_ci
   --explicit_defaults_for_timestamp=true
   --skip-host-cache
   --skip-name-resolve
  image: mysql:8.0.27
  environment:
   TZ: Asia/Shanghai
   MYSQL_ROOT_PASSWORD: saboran
  ports:
   - 3306:3306
  volumes:
   - ./data/mysql/data:/var/lib/mysql
   - ./data/mysql/config:/etc/mysql/conf.d
