version: '3'

networks:
  default:
    external:
      name: tools

services:
  redis:
    image: redis:4.0.13
    container_name: redis
    restart: always
    command: --requirepass saboran --appendonly yes
    ports:
      - 6379:6379
    volumes:
    - ./data:/data
